
  
name: Staging Build Pipeline

on:
  push:
    branches: 
      - develop

jobs:
  build:
    name: Marph project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build Docker image
        run: docker build -t registry.heroku.com/${{ secrets.HEROKU_APP }}/web:latest .

      - name: Docker image info
        run: docker images
