name: Pull request Pipeline

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: Marph project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build Docker image
        env:
          MORPHCLOUDS_URL: ${{ secrets.MORPHCLOUDS_URL }}
          MORPHCLOUDS_TOKEN: ${{ secrets.MORPHCLOUDS_TOKEN }}
        run: docker build --build-arg MORPHCLOUDS_URL=$MORPHCLOUDS_URL MORPHCLOUDS_TOKEN=$MORPHCLOUDS_TOKEN  -t registry.heroku.com/${{ secrets.HEROKU_APP }}/web:latest .

      - name: Docker image info
        run: docker images
