name: Pull request Pipeline

on:
  push:
    branches: 
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          
      - name: Build Docker image
        run: docker build -t registry.heroku.com/${{ secrets.HEROKU_APP }}/web:latest .

      - name: Docker image info
        run: docker images
